name: Preview Deployment (apps/web)
permissions:
  contents: read
on:
  push:
    branches-ignore:
      - main
    paths:
      - apps/web/**
      - packages/**
  workflow_dispatch:
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEB }}
      VERCEL_TELEMETRY_DISABLED: 1
      NEXT_TELEMETRY_DISABLED: 1
      TURBO_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Pull vercel environment information
        run: pnpm dlx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build project artifacts
        run: |
          pnpm build:web
          pnpm dlx vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy project artifacts to vercel
        run: |
          pnpm dlx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > domain.txt
          pnpm dlx vercel alias --scope=${{ secrets.VERCEL_ORG_ID }} --token=${{ secrets.VERCEL_TOKEN }} set `cat domain.txt` dev.powenel.com
